workflows:
  mazda_android:
    name: Mazda APK Workflow
    environment:
      flutter: stable
      android_signing:
        - mazda_key
      groups:
        - Mazda 
      
    scripts:
      - flutter clean
      - flutter pub get

      - name: Decode Keystore
        script: |
          cat >> "$CM_BUILD_DIR/project_directory/android/key.properties" <<EOF
          storePassword=$CM_KEYSTORE_PASSWORD
          keyPassword=$CM_KEY_PASSWORD
          keyAlias=$CM_KEY_ALIAS
          storeFile=$CM_KEYSTORE_PATH
          EOF 

      - name: Change Android app name
        script: sed -i.bak "s/android:label=\".*\"/android:label=\"$APP_NAME\"/g" android/app/src/main/AndroidManifest.xml

      - name: Unzip Nissan icons
        script: unzip -o assets/zips/assets_nissan.zip -d android/app/src/main/res/

      - flutter build apk

    artifacts:
      - build/**/outputs/apk/**/*.apk

  mazda_ios:
    name: Mazda IPA Workflow
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - Mazda 
    scripts:
      - flutter clean
      - flutter pub get
      - flutter build ipa
    artifacts:
      - build/ios/ipa/*.ipa

  nissan_android:
    name: Nissan APK Workflow
    environment:
      flutter: stable
      groups:
        - Nissan 
      
    scripts:
      - flutter clean
      - flutter pub get

      - name: Decode Keystore
        script: |
          cat >> "$CM_BUILD_DIR/project_directory/android/key.properties" <<EOF
          storePassword=$CM_KEYSTORE_PASSWORD
          keyPassword=$CM_KEY_PASSWORD
          keyAlias=$CM_KEY_ALIAS
          storeFile=$CM_KEYSTORE_PATH
          EOF

      - name: Change Android app name
        script: sed -i.bak "s/android:label=\".*\"/android:label=\"$APP_NAME\"/g" android/app/src/main/AndroidManifest.xml
      
      - name: Unzip Nissan icons
        script: unzip -o assets/zips/assets_nissan.zip -d android/app/src/main/res/

      - flutter build apk
      
    artifacts:
      - build/**/outputs/apk/**/*.apk

  nissan_ios:
    name: Nissan IPA Workflow
    environment:
      flutter: stable
      groups:
        - Nissan 
    scripts:
      - flutter clean
      - flutter pub get
      - flutter build ipa
    artifacts:
      - build/ios/ipa/*.ipa
